all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
all_joints_names:
- left_ear
- right_ear
- left_eye
- right_eye
- nose
- left_shoulder
- right_shoulder
- lower_neck
- left_elbow
- right_elbow
- left_wrist
- right_wrist
- left_hip
- right_hip
- left_knee
- right_knee
- left_ankle
- right_ankle
alpha_r: 0.02
apply_prob: 0.5
batch_size: 8
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_ml_comparison_6Mar11\ml_comparison_6_Charlotte95shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
global_scale: 0.8
init_weights: C:\Users\cw266\Anaconda3\envs\'DEEPLABCUT6'\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_ml_comparison_6Mar11\Documentation_data-ml_comparison_6_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: true
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_idchannel: 0
num_joints: 18
num_limbs: 54
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 1
  - 15
- - 1
  - 7
- - 1
  - 12
- - 2
  - 15
- - 15
  - 17
- - 11
  - 15
- - 5
  - 15
- - 14
  - 15
- - 13
  - 15
- - 4
  - 15
- - 6
  - 7
- - 6
  - 10
- - 6
  - 14
- - 4
  - 6
- - 6
  - 8
- - 7
  - 11
- - 5
  - 7
- - 4
  - 7
- - 2
  - 5
- - 2
  - 12
- - 2
  - 3
- - 16
  - 17
- - 9
  - 17
- - 14
  - 17
- - 12
  - 17
- - 3
  - 17
- - 13
  - 17
- - 0
  - 14
- - 0
  - 13
- - 0
  - 9
- - 0
  - 8
- - 0
  - 11
- - 0
  - 16
- - 0
  - 3
- - 12
  - 14
- - 3
  - 14
- - 8
  - 11
- - 8
  - 12
- - 8
  - 9
- - 4
  - 8
- - 11
  - 12
- - 4
  - 11
- - 13
  - 16
- - 10
  - 13
- - 9
  - 13
- - 9
  - 16
- - 12
  - 16
- - 5
  - 12
- - 10
  - 12
- - 5
  - 9
- - 4
  - 5
- - 9
  - 10
- - 3
  - 4
- - 3
  - 10
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: C:\Users\cw266\Videos\ml_comparison_6-Charlotte-2022-03-11
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
weigh_only_present_joints: false
